name: Build

on:
  push:
    branches:
      - main
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      INTEGRATION_TOKEN:
        required: true

# Update this environment variable to match the name of your AWS ECR for this application.
env:
  REPOSITORY_NAME: sample-nodejs-general
  APPLICATION_INTEGRATION_ID: 38ddcde8-56bc-4c28-8ff2-48e4b3016f52

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        registry-url: "https://npm.pkg.github.com"

    - name: Install libraries
      run: |
        npm install

    - name: Build
      run: |
        npm run build
      env:
        NODE_ENV: production

    - name: Prune dev libraries
      run: |
        npm prune
      env:
        NODE_ENV: production

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to AWS ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ env.REPOSITORY_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker image tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
        docker push $REGISTRY/$REPOSITORY:latest
      
    - name: Share the image with Skip the DevOps
      uses: skipthedevops/declare-process-version@v1
      with:
        integration-token: ${{ secrets.INTEGRATION_TOKEN }}
        application-integration-id: ${{ env.APPLICATION_INTEGRATION_ID }}
        tag: ${{ github.sha }}
        name: ${{ github.event.head_commit.message }}
        auto-deploy: true